### ISSUE TITLE
timestamp undefined

### ISSUE THREAD

**Issue by jsolderitsch** [IBM/customer-loyalty-program-hyperledger-fabric-VSCode#1]
I implemented the fabric locally and I did not see any errors.

My member made purchases and redeemed points but the transaction data is incorrect.
For example:
```
Points Earned Transactions

timeStamp: undefined
partner: Villanova01
member: 123456
points: 30
transactionName: undefined
transactionID: undefined


timeStamp: undefined
partner: Villanova01
member: 123456
points: 80
transactionName: undefined
transactionID: undefined
```

and 

```
Points Redeemed Transactions

timeStamp: undefined
partner: Villanova01
member: 123456
points: 50
transactionName: undefined
transactionID: undefined
```

Appreciate suggestions on how to fix.

**Comment by ash7594** [comment]
Hi @jsolderitsch , thanks for pointing out this bug.
It is now fixed, and the data should be able to find its way back in the UI.
