### ISSUE TITLE
Readme specifies wrong version of VSCode

### ISSUE THREAD

**Issue by nklincoln** [IBM/customer-loyalty-program-hyperledger-fabric-VSCode#14]
The current readme specifies `VSCode version 1.26 or greater`, but there is an *actual* requirement of `VS Code version 1.35.1 or greater` for the IBM Blockchain Platform extension.

If someone picks up an older version of VSCode, they won't be able to install the 1.0.x release of IBM Blockchain Platform

**Comment by sandhya-nayak** [comment]
Thanks for pointing this out.
#16 fixes this.

**Comment by sandhya-nayak** [comment]
This has been fixed in #16. Closing.
