### ISSUE TITLE
Application has references to Composer

### ISSUE THREAD

**Issue by nklincoln** [IBM/customer-loyalty-program-hyperledger-fabric-VSCode#15]
The application has a few references to Composer remaining:
- about.html - it does not use the Composer API, but the fabric network API
- index.html - same as above

Could be confusing to new users.

**Comment by sandhya-nayak** [comment]
Thanks for pointing this out.
#16 fixes this.

**Comment by sandhya-nayak** [comment]
This has been fixed in #16. Closing.
