### ISSUE TITLE
Documentation Related : Repository name not Correct in git clone command

### ISSUE THREAD

**Issue by singhrajgithub** [IBM/customer-loyalty-program-hyperledger-fabric-VSCode#2]
Hello Mate,,

Could you update repository name . It looks like you have updated repository name but in wiki it has old repo name.

current :  git clone https://github.com/IBM/customer-loyalty-program-hyperledger-fabric.git 
should be : git clone https://github.com/IBM/customer-loyalty-program-hyperledger-fabric-VSCode.git

Thanks

**Comment by ash7594** [comment]
Thanks for noticing. Resolved
