### ISSUE TITLE
Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by poky** [IBM/customer-loyalty-program-hyperledger-fabric-VSCode#7]
Hi, when I tried to create a new member and using it to sign in, however the browser throws this error:

![Screenshot from 2019-07-26 00-39-26](https://user-images.githubusercontent.com/138415/61892389-47dcda00-af3e-11e9-8769-07bd78c05b64.png)

And the Node console gives:

```
app running on port: 8000
memberData using param -  accountNumber: 111111 cardId: test
Wallet path: /home/lee/customer-loyalty-program-hyperledger-fabric-VSCode/web-app/wallet

Get member state 
2019-07-25T16:39:14.079Z - info: [TransactionEventHandler]: _strategySuccess: strategy success for transaction "bbf5b13f637a82ca8ad61cf6dc45bebe426a1a7e5e3792ec4ce7e5b345a345fb"
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.memberData (/home/lee/customer-loyalty-program-hyperledger-fabric-VSCode/web-app/network/network.js:371:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Wallet path: /home/lee/customer-loyalty-program-hyperledger-fabric-VSCode/web-app/wallet

Get use points transactions state for member 111111
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.usePointsTransactionsInfo (/home/lee/customer-loyalty-program-hyperledger-fabric-VSCode/web-app/network/network.js:539:36)
    at <anonymous>
(node:32527) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Can't set headers after they are sent.
(node:32527) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I'm using nodejs version 8.9.4 if that helps.

**Comment by PatelAshish1** [comment]
Using JSON.stringify(data);:

Full Source Code At [Here](https://icetutor.com/question/parsing-json-giving-unexpected-token-o-error/)

**Comment by nklincoln** [comment]
this is in quite a few places:
- getState.js (1 occurence)
- network.js (7 occurences)

There was a change in the chaincode return such that double parsing of the response is not needed (which is a good thing). This does now mean that this sample is broken until this issue is resolved.

**Comment by nklincoln** [comment]
@ash7594 @raheelzubairy ... this issue prevents the sample from working

**Comment by RabiRoshan** [comment]
I have fixed this issue by doing this:
Replace all occurrence of `JSON.parse(JSON.parse` by `JSON.parse` in  the file `web-app/network/network.js`.

**Comment by HardikKSavaliya** [comment]
Remove Dual JSON.parse, and it work fine for me as well.

**Comment by sandhya-nayak** [comment]
This issue has now been fixed.
